services:
  promocodefactory.webhost:
    image: ${DOCKER_REGISTRY-}promocodefactorywebhost
    build:
      context: .
      dockerfile: PromoCodeFactory.WebHost/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__PromoCodeFactoryDb=Host=postgres;Database=promocode_factory_db;Username=postgres;Password=password123;Port=5432
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure

  postgres:
    image: postgres:15
    container_name: promocode_postgres
    environment:
      POSTGRES_DB: promocode_factory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d promocode_factory_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge