name: .NET Tests

on:
  push:
    branches:
      - main
    paths:
      - 'Homeworks/UnitTests/src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Homeworks/UnitTests/src/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Homeworks/UnitTests/src

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # замени на свою версию SDK

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
